"""Generate AI plain-language summaries for merged district profiles.

Reads:
  data/processed/districts/<cds_code>.json   (merged + schema-validated profiles)
Writes:
  data/processed/districts/<cds_code>.json   (same file, with `ai_summaries` populated)
  data/processed/_ai_cache/<sha>_<key>_<prompt_version>.txt   (raw model output cache)

What we generate, per district:
  - `overview`                       — neutral 2-3 sentence factual snapshot
  - `what_this_means_for_parents`    — 3-4 sentence translation for caregivers

Why caching: each call costs money and time, and the underlying numbers only
change once a year. We hash the profile (excluding the AI-generated fields and
volatile fields like `build_provenance` / `last_updated`) and re-use the cached
output whenever the inputs are unchanged.

Secrets: ANTHROPIC_API_KEY must be set in the environment. The recommended
workflow is `doppler run -- python -m pipeline.enrichers.summarize`. If the
key is missing the script prints setup instructions and exits 1 without
mutating any files.

Usage:
    doppler run -- python -m pipeline.enrichers.summarize
    # or (local dev only): ANTHROPIC_API_KEY=sk-... python -m pipeline.enrichers.summarize
"""

from __future__ import annotations

import hashlib
import json
import os
import sys
from pathlib import Path

from pipeline.utils import utc_now_iso

REPO_ROOT = Path(__file__).resolve().parents[2]
DISTRICTS_DIR = REPO_ROOT / "data" / "processed" / "districts"
CACHE_DIR = REPO_ROOT / "data" / "processed" / "_ai_cache"

AI_MODEL = "claude-sonnet-4-6"
PROMPT_VERSION = "v1"
MAX_TOKENS = 600

AI_DISCLAIMER = (
    "This summary was generated by an AI model from the data points cited in "
    "this profile. The underlying numbers come from public government sources, "
    "but the narrative is AI-written and may contain inaccuracies. Verify "
    "specific claims directly with the school district before making decisions."
)

# Fields that are NOT part of the cache key — these change on every run even
# when the underlying data hasn't.
CACHE_EXCLUDE_TOP_LEVEL = {"ai_summaries", "build_provenance", "last_updated"}


SUMMARY_KEYS = ("overview", "what_this_means_for_parents")


SYSTEM_PROMPT = """You are writing plain-language data summaries for an
open, donation-funded directory that helps families of children with autism
and other disabilities compare California school districts.

Hard rules:
1. Only state facts that are explicitly present in the JSON profile provided.
   Never invent enrollment numbers, rates, program names, or staffing details.
2. If a field is missing or null, do not mention it. Say nothing rather than
   guess.
3. Do NOT rank, score, recommend, or warn against a district. Stay descriptive.
4. Use percentages (e.g., "85%") rather than decimals (e.g., "0.85"). Use
   absolute student counts as integers.
5. For Distance From Standard (DFS): negative = below grade level, positive =
   above grade level. The unit is "points" — say "X points below standard" or
   "X points above standard", not "X% below".
6. SWD = Students with Disabilities; this is a broad subgroup that includes
   autism but is not autism-specific.
7. Write at roughly an 8th-grade reading level. No marketing language."""


PROMPT_TEMPLATES: dict[str, str] = {
    "overview": """Write a neutral 2-3 sentence factual snapshot of this
district for the directory's "Overview" card. Lead with size and inclusion
posture if data is available. Mention the autism-specific inclusion rate
when present.

District profile JSON:
{profile_json}

Return only the summary text — no preamble, no quotes, no markdown.""",
    "what_this_means_for_parents": """Translate the profile below into 3-4
plain sentences for a parent of an autistic child who is researching whether
this district might be a good fit. Focus on:
  - What the autism inclusion rate suggests about typical placement
  - What SWD academic and behavioral outcomes look like relative to the
    all-students baseline (gap, not absolute judgment)
  - Anything notable but missing (e.g., "this profile does not yet include
    program-specific information") — but only mention gaps if relevant.

Do not give advice or recommendations. Describe what the data shows.

District profile JSON:
{profile_json}

Return only the summary text — no preamble, no quotes, no markdown.""",
}


def profile_cache_hash(profile: dict) -> str:
    """SHA-256 of the profile with volatile fields stripped, used as cache key."""
    stable = {k: v for k, v in profile.items() if k not in CACHE_EXCLUDE_TOP_LEVEL}
    payload = json.dumps(stable, sort_keys=True, separators=(",", ":")).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def cache_path(profile_sha: str, key: str) -> Path:
    return CACHE_DIR / f"{profile_sha}_{key}_{PROMPT_VERSION}.txt"


def load_cached(profile_sha: str, key: str) -> str | None:
    p = cache_path(profile_sha, key)
    if p.exists():
        return p.read_text().strip()
    return None


def save_cached(profile_sha: str, key: str, text: str) -> None:
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    cache_path(profile_sha, key).write_text(text.strip() + "\n")


def build_summary_input(profile: dict) -> dict:
    """Strip volatile/AI fields before sending to the model so the prompt stays focused."""
    return {k: v for k, v in profile.items() if k not in CACHE_EXCLUDE_TOP_LEVEL}


def call_anthropic(client, prompt: str) -> str:
    """Single non-streaming Messages API call. Returns the assistant text."""
    resp = client.messages.create(
        model=AI_MODEL,
        max_tokens=MAX_TOKENS,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": prompt}],
    )
    parts = [b.text for b in resp.content if getattr(b, "type", None) == "text"]
    return "".join(parts).strip()


def wrap_ai_generated(text: str, *, based_on_sources: list[str]) -> dict:
    """Wrap raw model output in the schema's AIGenerated shape."""
    return {
        "value": text,
        "ai_generated": True,
        "ai_model": AI_MODEL,
        "ai_generated_at": utc_now_iso(),
        "ai_disclaimer": AI_DISCLAIMER,
        "based_on_sources": based_on_sources,
    }


def enrich_profile(profile: dict, client) -> tuple[dict, dict[str, str]]:
    """Return (profile_with_ai_summaries, {key: 'cache_hit'|'generated'})."""
    sources = profile.get("data_sources_used", [])
    profile_sha = profile_cache_hash(profile)
    summary_input = build_summary_input(profile)
    profile_json = json.dumps(summary_input, indent=2, sort_keys=True)

    ai_summaries: dict = {}
    status: dict[str, str] = {}

    for key in SUMMARY_KEYS:
        cached = load_cached(profile_sha, key)
        if cached is not None:
            text = cached
            status[key] = "cache_hit"
        else:
            prompt = PROMPT_TEMPLATES[key].format(profile_json=profile_json)
            text = call_anthropic(client, prompt)
            save_cached(profile_sha, key, text)
            status[key] = "generated"
        ai_summaries[key] = wrap_ai_generated(text, based_on_sources=sources)

    out = dict(profile)
    out["ai_summaries"] = ai_summaries
    return out, status


def get_client():
    """Import the Anthropic SDK lazily so missing-deps fails with a friendly message."""
    try:
        from anthropic import Anthropic
    except ImportError:
        print("ERROR: anthropic SDK not installed. Run: pip install anthropic", file=sys.stderr)
        sys.exit(1)
    return Anthropic()


def main() -> int:
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print(
            "ERROR: ANTHROPIC_API_KEY is not set.\n\n"
            "Recommended (Doppler):\n"
            "  doppler run -- python -m pipeline.enrichers.summarize\n\n"
            "Local dev fallback:\n"
            "  ANTHROPIC_API_KEY=sk-ant-... python -m pipeline.enrichers.summarize\n\n"
            "See docs/SECURITY.md for the project's secret-management policy.",
            file=sys.stderr,
        )
        return 1

    profiles = sorted(DISTRICTS_DIR.glob("*.json"))
    if not profiles:
        print(f"No profiles found in {DISTRICTS_DIR}. Run the merge step first.", file=sys.stderr)
        return 1

    client = get_client()
    n_generated = 0
    n_cached = 0

    for path in profiles:
        profile = json.loads(path.read_text())
        cds = profile.get("cds_code", path.stem)
        name = profile.get("name", "<unknown>")

        enriched, status = enrich_profile(profile, client)
        path.write_text(json.dumps(enriched, indent=2, sort_keys=True))

        hits = [k for k, v in status.items() if v == "cache_hit"]
        gens = [k for k, v in status.items() if v == "generated"]
        n_cached += len(hits)
        n_generated += len(gens)
        marker = "CACHED" if not gens else "AI    "
        print(f"{marker} {cds} {name:<28} generated={len(gens)} cached={len(hits)}")

    print(f"\nDone. generated={n_generated} cached={n_cached} districts={len(profiles)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
